export const Labels = {
  people: {
    height: 'Altura',
    mass: 'Peso',
    hair_color: 'Cor do cabelo',
    skin_color: 'Cor da pele',
    eye_color: 'Cor dos olhos',
    birth_year: 'Ano de nascimento',
    gender: 'Género',
  },
  starships: {
    model: 'Modelo',
    manufacturer: 'Fabricante',
    cost_in_credits: 'Custo em créditos',
    length: 'Comprimento',
    max_atmosphering_speed: 'Velocidade máxima de atmosfera',
    crew: 'Tripulação',
    passengers: 'Passageiros',
    cargo_capacity: 'Capacidade de carga',
    consumables: 'Consumíveis',
    hyperdrive_rating: 'Classificação',
    MGLT: 'MGLT',
    starship_class: 'Classe',
  },
  species: {
    classification: 'Clasificação',
    designation: 'sentient',
    average_height: '180',
    hair_color: 'Cor do cabelo',
    skin_color: 'Cor da pele',
    eye_color: 'Cor dos olhos',
    average_lifespan: '120',
    language: 'Linguagem',
  },
  films: {
    episode_id: 'Episódio',
    opening_crawl: 'Rastreamento de abertura',
    director: 'Diretor',
    producer: 'Produtora',
    release_date: 'Data de lançamento',
  },
  vehicles: {
    manufacturer: 'Fabricante',
    cost_in_credits: 'Custo em créditos',
    length: 'Comprimento',
    max_atmosphering_speed: 'Velocidade máxima de atmosfera',
    crew: 'Tripulação',
    passengers: 'Passageiros',
    cargo_capacity: 'Capacidade de carga',
    consumables: 'Consumíveis',
    vehicle_class: 'Classe de veiculo',
  },
  pilots: {
    height: 'Altura',
    mass: 'Peso',
    hair_color: 'Cor do cabelo',
    skin_color: 'Cor da pele',
    eye_color: 'Cor dos olhos',
    birth_year: 'Ano de nascimento',
    gender: 'Género',
  },
  residents: {
    height: 'Altura',
    mass: 'Peso',
    hair_color: 'Cor do cabelo',
    skin_color: 'Cor da pele',
    eye_color: 'Cor dos olhos',
    birth_year: 'Ano de nascimento',
    gender: 'Género',
  },
  homeworld: {
    rotation_period: 'Período de rotação',
    orbital_period: 'Período orbital',
    diameter: 'Diâmetro',
    climate: 'Clima',
    gravity: 'Gravidade',
    terrain: 'Terreno',
    surface_water: 'Aguas superficiais',
    population: 'População',
  },
  planets: {
    rotation_period: 'Período de rotação',
    orbital_period: 'Período orbital',
    diameter: 'Diâmetro',
    climate: 'Clima',
    gravity: 'Gravidade',
    terrain: 'Terreno',
    surface_water: 'Aguas superficiais',
    population: 'População',
  },
};
